const AuthUseCase = require('../../usecase/auth')
const mockAuthRepo = require('../mock/repository.auth.mock')
const mockUserRepo = require('../mock/repository.user.mock')
const mockOTPRepo = require ('../mock/repository.otp.mock')
const avatar = require ('../../internal/constant/defaultImage')
const func = require('../../libs/function')